sudo: false
language: ruby
rvm:
  - 2.2.8
  - 2.2.9
  - 2.2.10
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.3.7
  - 2.4.0
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.5.0
  - 2.5.1
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
before_install: gem install bundler -v 1.16.2
